# Change these first
owner: abelfleitas # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository
user-agent: abelfleitas

sites:    
  - name: Signal Market
    url: https://signalmarket.us   
    
  - name: Tuwex Inc
    url: https://tuwexinc.com

  - name: Admin Tuwex Inc
    url: https://admin.tuwexinc.com

  - name: Admin Sandbox Tuwex Inc
    url: https://admin-dev.tuwexinc.com    
    
  - name: Tuwexinc API
    url: https://api.tuwexinc.com/health

  - name: Chart Tuwex Inc
    url: https://chart.tuwexinc.com  

  - name: Ticket Tuwex Inc
    url: https://ticket.tuwexinc.com    
  
  - name: API Bot PHP
    url: https://apibotphp2.herokuapp.com/public/
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.tuwexinc.com
  #baseUrl: status
  logoUrl: https://raw.githubusercontent.com/abelfleitas/status/master/assets/logo.svg
  name: Status | Tuwex Inc
  #introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  #introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  theme: night 
  favicon: https://raw.githubusercontent.com/abelfleitas/status/master/assets/favicon.ico
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
